PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?sequence ?cueLabel ?cueText ?inferenceLabel ?interpretationLabel ?status
WHERE {
  ?cue lig:supportsInference ?inference .
  ?inference lig:licensesInterpretation ?interpretation .

  OPTIONAL { ?inference lig:hasSequenceNumber ?sequence . }
  OPTIONAL { ?cue rdfs:label ?cueLabel . }
  OPTIONAL { ?cue lig:hasTextualContent ?cueText . }
  OPTIONAL { ?inference rdfs:label ?inferenceLabel . }
  OPTIONAL { ?interpretation rdfs:label ?interpretationLabel . }
  OPTIONAL { ?interpretation lig:hasInterpretiveStatus ?status . }
}
ORDER BY ?sequence ?cueLabel ?inferenceLabel ?interpretationLabel
