# CQ6: What is the interpretive status of each interpretation?
# Purpose: Check that the KG distinguishes licensed, alternative, and conjectural interpretations.
# KG pattern: Interpretation -> hasInterpretiveStatus -> literal
# Expected result: A table listing each interpretation and its interpretive status.

PREFIX lig: <https://lectoringraphula.org/ontology#>
PREFIX hmt: <https://lectoringraphula.org/handmaid#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?interpretationLabel ?status
WHERE {
  ?interpretation lig:hasInterpretiveStatus ?status .

  OPTIONAL { ?interpretation rdfs:label ?interpretationLabel . }
}
ORDER BY ?status ?interpretationLabel
